const UsersData = [
  {
    id: "#SK2540",
    name: "Neal Matthews",
    email: "neal@gmail.com",
    phone: "555-444-222",
    type: "Customer",
    phoneverified: false,
    emailverified: false,
    twofactorenabled: false,
    enabled: false,
  },
  {
    id: "#SK2545",
    name: "Nitin Gail",
    email: "nitis@gmail.com",
    phone: "999-111-222",
    type: "Sales User",
    phoneverified: true,
    emailverified: true,
    twofactorenabled: true,
    enabled: false,
  },
  {
    id: "#SK2545",
    name: "Nitin Gail",
    email: "nitis@gmail.com",
    phone: "999-111-222",
    type: "Warehouse User",
    phoneverified: true,
    emailverified: true,
    twofactorenabled: true,
    enabled: false,
  },
  {
    id: "#SK2545",
    name: "Nitin Gail",
    email: "nitis@gmail.com",
    phone: "999-111-222",
    type: "Accounting User",
    phoneverified: true,
    emailverified: true,
    twofactorenabled: true,
    enabled: false,
  },
  {
    id: "#SK2545",
    name: "Nitin Gail",
    email: "nitis@gmail.com",
    phone: "999-111-222",
    type: "Office User",
    phoneverified: true,
    emailverified: true,
    twofactorenabled: true,
    enabled: false,
  },
];

export { UsersData };
